#!/bin/bash

echo "Generating ddcloud.inventory..."
./generate-inventory > ./ddcloud.inventory

# Use SSH key file.
echo "Step 1 of 5 - configuring cluster machines to use SSH keyfile (initial password can be found in mantl.tf)..."
ansible all -u root -k -m authorized_key -a "user=root key='{{ lookup('file', '$HOME/.ssh/id_rsa.pub') }}'"

echo "Step 1 of 5 complete"

# Set host names.
echo "Step 2 of 5 - configuring cluster machine host names..."
ansible all -u root -a "hostnamectl set-hostname {{ inventory_hostname }}" 

echo "Expect errors from the next command since we're rebooting the target servers..."
ansible all -u root -e 'ignore_errors=true' -a 'nohup bash -c "sleep 2s && reboot" &'

echo "Step 2 of 5 complete - wait for reboots and then run build-cluster-step3"
